### ISSUE TITLE
False Negative: `Transaction failed. Please try again.`

### ISSUE THREAD

**Issue by chrishobcroft** [openhouse-project/openhouse-frontend#8] opened 2021-06-23 15:45 UTC
When using the deployed instance of openhouse-frontend, an unexpected error was encountered.

The app reported `Transaction failed. Please try again.` in the frontend.

The transaction had been successfully mined shortly after it was broadcast.

# Observed behaviour

1. Load https://openhouse.col*******ory.io/

2. Click "Connect", and connect wallet.

3. Enter a name for the conference room and click Join

4. Click "Confirm" in MetaMask.

5. Observe in the console that the app has received the transaction hash

6. Observe that MetaMask reports that the transaction has been confirmed, which is [confirmed on Etherscan](https://rinkeby.etherscan.io/tx/0xbf4b704db43a58dadc146dc82fce7ec01d9fc88d56b3dc0b8f98f21dbf39d4a3)

7. Wait around 10 minutes

8. Observe the app reports `Transaction failed. Please try again.`

9. UNEXPECTED BEHAVIOUR: Observe the following message in the console: `Error: Transaction was not mined within 50 blocks, please make sure your transaction was properly sent. Be aware that it might still be mined!`

# Expected behaviour

I expect that at (or before) step 6, the application allows a user to be permitted into a video chat room. This is as per 

# Notes

The console shows the transaction hash to be [0x0e4299698987e8321086273b7b50b665de10bbf7d5b9a6b2128561167a36fa4d](https://rinkeby.etherscan.io/tx/0x0e4299698987e8321086273b7b50b665de10bbf7d5b9a6b2128561167a36fa4d) which was mined shortly after being submitted.

# Screenshots

![image](https://user-images.githubusercontent.com/2212651/123254606-7d184b00-d50c-11eb-86c8-6c22f0d026d4.png)

**Comment by jpetrich** [comment] 2021-06-28 02:51
It would be great to know if anyone can still reproduce - since #12 was merged in, I haven't been able to reproduce, though I was able to reproduce this consistently before.

@chrishobcroft since you seem the best at reproducing, please close this if you no longer have this issue :)

**Comment by chrishobcroft** [comment] 2021-07-01 14:26
Closing - unable to reproduce on latest releases.

**Closed** 2021-07-01 14:27 UTC
